/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rv_fpga_plc_ide_helper_compile_c_file */

#ifndef _Included_rv_fpga_plc_ide_helper_compile_c_file
#define _Included_rv_fpga_plc_ide_helper_compile_c_file
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rv_fpga_plc_ide_helper_compile_c_file
 * Method:    compile_c_to_mif
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_rv_1fpga_1plc_1ide_helper_compile_1c_1file_compile_1c_1to_1mif
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     rv_fpga_plc_ide_helper_compile_c_file
 * Method:    compile_download_to_soc
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_rv_1fpga_1plc_1ide_helper_compile_1c_1file_compile_1download_1to_1soc
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
