/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rv_fpga_plc_ide_helper_compile_c_file */

#ifndef _Included_rv_fpga_plc_ide_helper_compile_c_file
#define _Included_rv_fpga_plc_ide_helper_compile_c_file
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rv_fpga_plc_ide_helper_compile_c_file
 * Method:    compile_c_to_asm
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_rv_1fpga_1plc_1ide_helper_compile_1c_1file_compile_1c_1to_1asm
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rv_fpga_plc_ide_helper_compile_c_file
 * Method:    compile_c_to_hex
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_rv_1fpga_1plc_1ide_helper_compile_1c_1file_compile_1c_1to_1hex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rv_fpga_plc_ide_helper_compile_c_file
 * Method:    test_func
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rv_1fpga_1plc_1ide_helper_compile_1c_1file_test_1func
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
